### ISSUE TITLE
Load time/white screen between each photo for sliders

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#31]
Can we preload the next photo in line for the sliders? Seems to have a 0.5 sec delay where the screen is white before the image loads. This happens at Portfolio and Homepage. 

Does it on Mobile and Desktop, but definitely more noticeable on mobile.

**Comment by matt-cook** [comment]
Could force load all images on initial load (which is probably even worse
than the 0.5 sec delay, since that could be a lot of images to download
immediately on a mobile device):
http://stackoverflow.com/questions/22752711/bootstrap-carousel-make-download-next-image-when-using-background-image-on-div

Alternatively, smart lazy-loading the upcoming images would be ideal but
more complex:
http://www.maurizioconventi.com/2012/06/12/how-to-create-a-lazy-load-carousel-with-twitter-bootstrap/

**Comment by magnifiedjoy** [comment]
Do you think it's any worse than a blog post with an average of 100 <img src> tag?

Homepage probably would not be more than 6 slides for the carousel. Portfolio is around 20.

**Comment by magnifiedjoy** [comment]
Maybe we should implement site wide lazy load, considering how image heavy the site will be especially on the blog posts

**Comment by matt-cook** [comment]
Perhaps, also don't want to "over-optimize".. or solve problems we're not
actually having (post pages loading too slowly). Modern browsers do a
pretty good job not loading images you're not actually viewing.. which is
why the home/portfolio carousel images don't load until they show up.

I'm also a bit more concerned about making sure the homepage loads quickly
since the user hasn't take any action to indicate they actually want to
download a bunch of images (on the post pages they're clearly there to see
a bunch of images).

For now, best solution is probably to make sure all images on
home/portfolio are preloaded.

**Comment by matt-cook** [comment]
open a new issue if load times are too slow on any pages
