### ISSUE TITLE
Instagram feed broke

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#34]
Instagram feed in footer is missing now.

**Comment by matt-cook** [comment]
Instagram service is returning an error. Could be due to over-use by our
API key (doubtful, since we get something like 5,000 requests per hour) or
more likely their servers are down for the moment. Especially since there
developer documentation page is currently showing a 500 error:

http://instagram.com/developer/endpoints/

http://stackoverflow.com/questions/19822825/http-503-on-instagram-api-requests

Lets check again in a few minutes/hours.

**Comment by matt-cook** [comment]
ah hem. *their

**Comment by magnifiedjoy** [comment]
Cool, glad to hear it's their fault!

http://www.magnifiedjoy.com/
WEDDING · BOUDOIR · WORLDWIDE https://www.facebook.com/magnifiedjoy
Facebook https://www.facebook.com/magnifiedjoy
http://instagram.com/magnifiedjoyInstagram
http://instagram.com/magnifiedjoy http://www.twitter.com/magnifiedjoy
Twitter http://www.twitter.com/magnifiedjoy
https://google.com/+MagnifiedjoyphotographyGoogle Plus
https://google.com/+Magnifiedjoyphotography
http://www.yelp.com/biz/magnified-joy-photography-el-cerritoYelp
http://www.yelp.com/biz/magnified-joy-photography-el-cerrito
http://www.magnifiedjoy.com/Website http://www.magnifiedjoy.com/

**Comment by matt-cook** [comment]
Looks like it's back now.
